### ISSUE TITLE
1.0.0 Release Roadmap

### ISSUE THREAD

**Issue by OzairP** [OzairP/tslint-modern-react#1]
## Misc

- [x] Upgrade dependencies, add prettier, update README.
- [ ] Write docs

## Rule Configurations

- [ ] `tslint-modern-react` or `tslint-modern-react:auto` — Infers React version from `require('react').version`
- [ ] `tslint-modern-react:16.7` — React v16.7 (hooks)
- [ ] `tslint-modern-react:16.6` — React v16.6...
- [ ] `tslint-modern-react:16.4`
- [ ] `tslint-modern-react:16.3`
- [ ] `tslint-modern-react:16.2`
- [ ] `tslint-modern-react:16.0`

#### Maintainability
- [ ] `react-ban-proptypes` — Ban using propTypes
- [ ] `react-ban-untyped-default-props` — [See](https://github.com/palantir/tslint-react/issues/169)
- [ ] `react-ban-untyped-contexttype` — [See](https://reactjs.org/blog/2018/10/23/react-v-16-6.html#static-contexttype), only in v16.6+
- [ ] `react-ban-untyped-derived-state-props` — Ban untyped `static getDerivedStateFromProps`, only in v16.3+
- [ ] `react-ban-untyped-derived-state-error` — ban untyped `static getDerivedStateFromError`, only in v16.6+

#### Style
- [ ] `react-sort-prop-interface` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-prop-types.md)

##### From `eslint-plugin-react`
- [x] `react-prefer-es6-class` — Use ES6 class over `createReactClass` function.
- [ ] `react-sort-lifecycles` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md)
- [ ] `react-sort-default-props` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-prop-types.md)
- [ ] `react-fragment-style` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md)
##### From `tslint-react` issues
- [ ] `react-method-name-style` — [See](https://github.com/palantir/tslint-react/issues/10)
##### Other
- [ ] `react-no-constructor-state-init` — Ban initializing state from constructor

##### From `eslint-plugin-react`
- [ ] `react-ban-dom-props` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-dom-props.md), using `tslint-react`@`jsx-ban-props`
- [ ] `react-ban-access-state-in-setstate` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-access-state-in-setstate.md)
- [ ] `react-ban-array-index-as-key` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md)
- [ ] `react-ban-children-prop` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-children-prop.md)
- [ ] `react-ban-dangerous-props` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-danger.md)
- [ ] `react-ban-setstate-in-mount` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-did-mount-set-state.md)
- [ ] `react-ban-setstate-in-didupdate` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-did-update-set-state.md)
- [ ] `react-ban-direct-state-mutation` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-direct-mutation-state.md)
- [ ] `react-ban-multi-comp` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-multi-comp.md)
- [ ] `react-ban-pointless-purecomponent` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-redundant-should-component-update.md)
- [ ] `react-ban-this-in-func-comp` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-this-in-sfc.md)
- [ ] `react-ban-unused-state` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unused-state.md)
- [ ] `react-ban-setstate-in-willupdate` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-will-update-set-state.md)
- [ ] `react-ban-useless-class-component` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-stateless-function.md)
- [ ] `react-ban-void-render-func` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-render-return.md)
- [ ] `react-ban-unnamed-anonymous-comp` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/display-name.md) but do ban only if the component is anonymous
- [ ] `react-dom-ban-render-return` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-render-return-value.md)
##### From `tslint-react` issues
- [ ] `react-ban-unused-props` — [See](https://github.com/palantir/tslint-react/issues/151)
##### Other
- [ ] `react-ban-deprecated-lifecycles` —  [See](https://reactjs.org/blog/2018/03/29/react-v-16-3.html), in v16.3+ deprecate: `componentWillMount`, `componentWillChange` and `componentWillRecieveProps`
- [ ] `react-ban-callback-ref` — [See](https://reactjs.org/blog/2018/03/29/react-v-16-3.html#createref-api), only in 16.3+
- [ ] `react-ban-direct-prop-compare-in-derived-state-props` — [See](https://reactjs.org/blog/2018/05/23/react-v-16-4.html#2-compare-incoming-props-to-previous-props-when-computing-controlled-values), only in v16.4+
- [ ] `react-ban-find-dom-node` — [See](https://reactjs.org/blog/2018/10/23/react-v-16-6.html#deprecations-in-strictmode), only in v16.6+
- [ ] `react-ban-legacy-context` — [See](https://reactjs.org/blog/2018/10/23/react-v-16-6.html#deprecations-in-strictmode), only in 16.6+
- [ ] `react-ban-force-update` — Ban the use of `forceUpdate`
- [ ] `react-ban-state-init-from-props` — Bans initializing state with props. Use `getDerivedStateFromProps` in v16.3+ or `componentWillReceiveProps` in 16.2 and below

##### From `eslint-plugin-react`
- [ ] `react-check-typos` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-typos.md)
- [ ] `react-check-unescaped-attr` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md)
- [ ] `jsx-check-bad-comment` — [See](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-comment-textnodes.md)
##### Other
- [ ] `react-hooks-only-top-level` — [See](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level), only in v16.7+
- [ ] `react-hooks-only-func-comp` — [See](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-from-react-functions), only in v16.7+
